<?php
		      return array (
  'admin_password' => 'aaaaaa',
  'db_user' => 'root',
  'db_password' => '',
  'db_name' => 'btc',
  'db_host' => 'localhost',
  'btc_protocol' => 'http',
  'btc_user' => 'root',
  'btc_password' => 'aaa',
  'btc_host' => 'localhost',
  'btc_port' => '18332',
  'text_logo' => 'PHPCoins',
  'site_name' => 'PHPCoins',
  'smtp_host' => 'smtp.yeah.net',
  'smtp_port' => '25',
  'smtp_user' => 'phpcoins@yeah.net',
  'smtp_password' => 'abcdef',
  'btc_decimal' => '8',
);